### ISSUE TITLE
Melhorar orientações de SETUP branch `install-django`

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/sima#4]

**Comment by gabrielbdornas** [comment]
@raianecardoso, acredito que após [este commit](https://github.com/automatiza-mg/sima/commit/a0cb51d73484dbd78f590e61d5144557fa6edcce) podemos fechar este Issue, o que acha?

**Comment by raianecardoso** [comment]
Concordo!

**Comment by gabrielbdornas** [comment]
@raianecardoso, lembrar de incluir o branch `install-django` no README.md

**Comment by gabrielbdornas** [comment]
@raianecardoso, após #10, este Issue issue não faz mais sentido.
