### ISSUE TITLE
Erro de migração: It is impossible to add a non-nullable field without specifying a default.

### ISSUE THREAD

**Issue by raianecardoso** [automatiza-mg/sima#6]
<img width="1182" alt="Captura de Tela 2024-07-23 às 15 45 15" src="https://github.com/user-attachments/assets/335ca033-4e54-4fd1-b0bc-915df2cf0f3c">

**Comment by gabrielbdornas** [comment]
@raianecardoso, descobrimos que ele não deixa rodar a migração pois os novos campos não podem ser nulos e em nossas tabelas já existiam registros. Sendo assim, temos que especificar o valor a ser preenchido nestes registros existentes para os novos campos que **não  podem ser nulos**.
