### ISSUE TITLE
Feedback SIMA - Django

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/sima#7]
@automatiza-mg/dcd, conforme solicitado ontem em nosso encontro do dia 24/07/2024 no Uluru, @raianecardoso e eu gostaríamos de um apoio de todos para o feedback da construção desta ferramenta. Acredito que cada um poderá incluir nos comentários abaixo dúvidas, sugestões e/ou outros pontos referentes à fase atual de construção da ferramenta SIMA[^1].

❗  Atualização: Usar o site https://sima-test.onrender.com/admin !! 

[^1]: Sugestões de novos nomes também são bem vindas.

**Comment by raianecardoso** [comment]
### Aproveito para registrar algumas sugestões comentadas ontem: 

- Dentre as possíveis oportunidades, renomear 'autogerada/ autogeminada' para 'espontânea';
- Renomear tabelas do PT para EN;

**Comment by gabrielbdornas** [comment]
@raianecardoso, logins e senhas criados para toda equipe @automatiza-mg/dcd. Sendo assim, tudo pronto para testes a serem realizados no webnar do dia 09/08/2024!

**Comment by Andrelamor** [comment]
> Ao tentar criar os usuários via migração tive um problema solucionado pelo chatGPT:
> 
> > Ensure the user is marked as is_staff and is_superuser in the database. The Django admin site requires users to have these flags set to True for admin access.
> 
> @raianecardoso, logins e senhas criados para toda equipe @automatiza-mg/dcd. Sendo assim, tudo pronto para testes a serem realizados no webnar do dia 09/08/2024!

acompanhei o webnar e fiz o setup do README, para exercitar e ter uma cópia local do repositório para possíveis usos futuros: 
![image](https://github.com/user-attachments/assets/9c876f40-7216-40d1-8f86-6b936d84196c)

**Comment by raianecardoso** [comment]
> > Ao tentar criar os usuários via migração tive um problema solucionado pelo chatGPT:
> > > Ensure the user is marked as is_staff and is_superuser in the database. The Django admin site requires users to have these flags set to True for admin access.
> > 
> > 
> > @raianecardoso, logins e senhas criados para toda equipe @automatiza-mg/dcd. Sendo assim, tudo pronto para testes a serem realizados no webnar do dia 09/08/2024!
> 
> acompanhei o webnar e fiz o setup do README, para exercitar e ter uma cópia local do repositório para possíveis usos futuros: ![image](https://private-user-images.githubusercontent.com/52294411/356664413-9c876f40-7216-40d1-8f86-6b936d84196c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjQ0MjUsIm5iZiI6MTcyMzIyNDEyNSwicGF0aCI6Ii81MjI5NDQxMS8zNTY2NjQ0MTMtOWM4NzZmNDAtNzIxNi00MGQxLThmODYtNmI5MzZkODQxOTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE3MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMTlmZjI3ZjI5YmZhYWQxMzY2MGViYWRlOGFhYjRmZmYwNjE4MTc0MDE2ODY1NmJhNjQ2NTAxN2ZmOWQ0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZPmeAuUQHJ_P9UEZL7MLzjdGupVTtA-HF216S1l0JI)

@Andrelamor, tenta colocar no final da url  ```/admin```  e veja se funciona!

**Comment by Andrelamor** [comment]
> > > Ao tentar criar os usuários via migração tive um problema solucionado pelo chatGPT:
> > > > Ensure the user is marked as is_staff and is_superuser in the database. The Django admin site requires users to have these flags set to True for admin access.
> > > 
> > > 
> > > @raianecardoso, logins e senhas criados para toda equipe @automatiza-mg/dcd. Sendo assim, tudo pronto para testes a serem realizados no webnar do dia 09/08/2024!
> > 
> > 
> > acompanhei o webnar e fiz o setup do README, para exercitar e ter uma cópia local do repositório para possíveis usos futuros: ![image](https://private-user-images.githubusercontent.com/52294411/356664413-9c876f40-7216-40d1-8f86-6b936d84196c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjQ0MjUsIm5iZiI6MTcyMzIyNDEyNSwicGF0aCI6Ii81MjI5NDQxMS8zNTY2NjQ0MTMtOWM4NzZmNDAtNzIxNi00MGQxLThmODYtNmI5MzZkODQxOTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE3MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMTlmZjI3ZjI5YmZhYWQxMzY2MGViYWRlOGFhYjRmZmYwNjE4MTc0MDE2ODY1NmJhNjQ2NTAxN2ZmOWQ0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZPmeAuUQHJ_P9UEZL7MLzjdGupVTtA-HF216S1l0JI)
> 
> @Andrelamor, tenta colocar no final da url `/admin` e veja se funciona!

![image](https://github.com/user-attachments/assets/19b8b403-2af2-4cba-b8a3-bd34021efbb3)

**Comment by raianecardoso** [comment]
> > > > Ao tentar criar os usuários via migração tive um problema solucionado pelo chatGPT:
> > > > > Ensure the user is marked as is_staff and is_superuser in the database. The Django admin site requires users to have these flags set to True for admin access.
> > > > 
> > > > 
> > > > @raianecardoso, logins e senhas criados para toda equipe @automatiza-mg/dcd. Sendo assim, tudo pronto para testes a serem realizados no webnar do dia 09/08/2024!
> > > 
> > > 
> > > acompanhei o webnar e fiz o setup do README, para exercitar e ter uma cópia local do repositório para possíveis usos futuros: ![image](https://private-user-images.githubusercontent.com/52294411/356664413-9c876f40-7216-40d1-8f86-6b936d84196c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjQ0MjUsIm5iZiI6MTcyMzIyNDEyNSwicGF0aCI6Ii81MjI5NDQxMS8zNTY2NjQ0MTMtOWM4NzZmNDAtNzIxNi00MGQxLThmODYtNmI5MzZkODQxOTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE3MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMTlmZjI3ZjI5YmZhYWQxMzY2MGViYWRlOGFhYjRmZmYwNjE4MTc0MDE2ODY1NmJhNjQ2NTAxN2ZmOWQ0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZPmeAuUQHJ_P9UEZL7MLzjdGupVTtA-HF216S1l0JI)
> > 
> > 
> > @Andrelamor, tenta colocar no final da url `/admin` e veja se funciona!
> 
> ![image](https://private-user-images.githubusercontent.com/52294411/357549482-19b8b403-2af2-4cba-b8a3-bd34021efbb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDYyMjcsIm5iZiI6MTcyMzY0NTkyNywicGF0aCI6Ii81MjI5NDQxMS8zNTc1NDk0ODItMTliOGI0MDMtMmFmMi00Y2JhLWI4YTMtYmQzNDAyMWVmYmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE0MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOTM4NjQ5MjE3NmQ2NzFhMDNkODI3NDk5ZGMyNjNjMDZhZWE1ZjBlYThkYWI3NTM0NGIyMTJkYmRlYTY4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cY-x-IH8_rHoNZR2jNvG_OFXcGdAr1YYl0f_wmYh55Y)

Deu certo, certo? Você tinha as credenciais?

**Comment by Andrelamor** [comment]
> > > > > Ao tentar criar os usuários via migração tive um problema solucionado pelo chatGPT:
> > > > > > Ensure the user is marked as is_staff and is_superuser in the database. The Django admin site requires users to have these flags set to True for admin access.
> > > > > 
> > > > > 
> > > > > @raianecardoso, logins e senhas criados para toda equipe @automatiza-mg/dcd. Sendo assim, tudo pronto para testes a serem realizados no webnar do dia 09/08/2024!
> > > > 
> > > > 
> > > > acompanhei o webnar e fiz o setup do README, para exercitar e ter uma cópia local do repositório para possíveis usos futuros: ![image](https://private-user-images.githubusercontent.com/52294411/356664413-9c876f40-7216-40d1-8f86-6b936d84196c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjQ0MjUsIm5iZiI6MTcyMzIyNDEyNSwicGF0aCI6Ii81MjI5NDQxMS8zNTY2NjQ0MTMtOWM4NzZmNDAtNzIxNi00MGQxLThmODYtNmI5MzZkODQxOTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE3MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMTlmZjI3ZjI5YmZhYWQxMzY2MGViYWRlOGFhYjRmZmYwNjE4MTc0MDE2ODY1NmJhNjQ2NTAxN2ZmOWQ0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZPmeAuUQHJ_P9UEZL7MLzjdGupVTtA-HF216S1l0JI)
> > > 
> > > 
> > > @Andrelamor, tenta colocar no final da url `/admin` e veja se funciona!
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/52294411/357549482-19b8b403-2af2-4cba-b8a3-bd34021efbb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDYyMjcsIm5iZiI6MTcyMzY0NTkyNywicGF0aCI6Ii81MjI5NDQxMS8zNTc1NDk0ODItMTliOGI0MDMtMmFmMi00Y2JhLWI4YTMtYmQzNDAyMWVmYmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE0MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOTM4NjQ5MjE3NmQ2NzFhMDNkODI3NDk5ZGMyNjNjMDZhZWE1ZjBlYThkYWI3NTM0NGIyMTJkYmRlYTY4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cY-x-IH8_rHoNZR2jNvG_OFXcGdAr1YYl0f_wmYh55Y)
> 
> Deu certo, certo? Você tinha as credenciais?

@raianecardoso não lembhro a senha que usamos no webnar da última sexta; 
mas na verdade, esse issue ainda está ativo, de fato? ou o feedback de que trata o título já não passou pro https://github.com/automatiza-mg/sima/issues/13?

**Comment by raianecardoso** [comment]
@Andrelamor, vou te mandar a senha pelo MS Teams. Sim, passou para o #13. Assim, vou fechar esse issue com este comentário.
