### ISSUE TITLE
Superuser creation skipped due to not running in a TTY. You can run manage.py createsuperuser in your project to create one manually.

### ISSUE THREAD

**Issue by gabrielbdornas** [automatiza-mg/sima#8]
Erro ocorrido com @halvesromano. [Stackoverflow utilizado](https://stackoverflow.com/questions/32532900/not-able-to-create-super-user-with-django-manage-py).

**Necessidade de documentar** a inclusão `winpty` antes de `python`.

**Comment by raianecardoso** [comment]
@gabrielbdornas documentar isso nas orientações de setup (read.me)?

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas documentar isso nas orientações de setup (read.me)?

Acredito que seria bom sim. Penso que em formato de nota de rodapé. O que acha?
